@url = http://localhost:33333/api/auth
@json = Content-Type: application/json

### 列表
get {{url}}

### 显示
get {{url}}/1

### 修改
put {{url}}/1
{{json}}

{
    "manager":"吴超"
}

### 创建
post {{url}}
{{json}}

{
    "label":"西安分公司",
    "pid":"1"
}

### 删除
delete {{url}}/8