@url = http://localhost:33333/api
@json = Content-Type: application/json

### 首页
get {{url}}

### 全部用户
get {{url}}/users

### 注册
post {{url}}/register
{{json}}

{
    "username":"usre1",
    "password":"123456",
    "style":"staff"
}


### 登录
post {{url}}/login
{{json}}

{
    "username":"root",
    "password":"admin"
}

### 刷新token
get {{url}}/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjMwOTgzZWQ1ZjAxNDUwYzM2YjgxNyIsImlhdCI6MTYwMDM1NzQwNywiZXhwIjoxNjAwMzYxMDA3fQ.pRAjCo5bmQOB5uzPli7_r_yPUH3U-V4yaOQmRaeZHVo


### 导航菜单
get {{url}}/navs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjMwOTgzZWQ1ZjAxNDUwYzM2YjgxNyIsImlhdCI6MTYwMDM1NzQwNywiZXhwIjoxNjAwMzYxMDA3fQ.pRAjCo5bmQOB5uzPli7_r_yPUH3U-V4yaOQmRaeZHVo


### 初始化
put {{url}}/init


### 表格配置
get {{url}}/metatable/:id

### 表单配置
get {{url}}/metaform/:id