@url = http://localhost:33333/api/res
@json = Content-Type: application/json


### 列表
get {{url}}

### 查询，只按label模糊查询
get {{url}}
{{json}}

{
    "label":"基础"
}


### 显示
get {{url}}/5f62e92d731aed26f835f92a

### 修改
put {{url}}/5f62e92d731aed26f835f92a
{{json}}

{
    "label":"基础设置"
}

### 新建
post {{url}}
{{json}}

{
    "label":"测试1122",
    "pid":"5f62ec98b3c5f44420cb8e10"
}

### 删除
delete {{url}}/5f62ebf6683c084b68462488