@url = http://localhost:33333/api/role
@json = Content-Type: application/json

### 列表
get {{url}}

### 查找
get {{url}}/5f63125225c7dd3f2c89e6d0

### 修改
put {{url}}/5f63125225c7dd3f2c89e6d0
{{json}}

{
    "icon":"aaaa"
}

### 新增
post {{url}}
{{json}}

{
    "label":"大数据讲师"
}

### 删除
delete {{url}}/5f63162e9bf25d31c8b41c3f