@url = http://localhost:33333/api/student
@json = Content-Type: application/json

### 学生列表
get {{url}}

### 显示
get {{url}}/5f62f93a123fd24e1438a8e1

### 修改
put {{url}}/5f62f93a123fd24e1438a8e1
{{json}}

{"realname":"我是学生"}

### 创建学生
post {{url}}
{{json}}

{
    "username":"student1",
    "password":"student1",
    "style":"student"
}

### 删除
delete {{url}}/5f62fb1c9af3ff423817df69