@url = http://localhost:33333/api/student
@json = Content-Type: application/json

### 学生列表
get {{url}}

### 显示
get {{url}}/4

### 修改
put {{url}}/4
{{json}}

{"realname":"我是学生"}

### 创建学生
post {{url}}
{{json}}

{
    "realname":"student1",
    "username":"student1",
    "password":"student1",
    "style":"student",
    "status":"在岗"
}

### 删除
delete {{url}}/10