@url = http://localhost:33333/api/user
@json = Content-Type: application/json

### 员工列表
get {{url}}/staff

### 学生列表
get {{url}}/student

### 显示
get {{url}}/5f62f93a123fd24e1438a8e1

### 修改
put {{url}}/5f62f93a123fd24e1438a8e1
{{json}}

{"realname":"我是学生"}

### 创建员工
post {{url}}
{{json}}

{
    "username":"staff1",
    "password":"staff1",
    "style":"staff"
}

### 创建学生
post {{url}}
{{json}}

{
    "username":"stu1",
    "password":"stu1",
    "style":"student"
}

### 删除
delete {{url}}/5f62fb1c9af3ff423817df69