@url = http://localhost:33333/api/res
@json = Content-Type: application/json


### 列表
get {{url}}

### 查询，只按label模糊查询
get {{url}}
{{json}}

{
    "label":"基础"
}


### 显示
get {{url}}/2

### 修改
put {{url}}/2
{{json}}

{
    "label":"教务设置"
}

### 新建
post {{url}}
{{json}}

{
    "label":"测试1122",
    "pid":"1"
}

### 删除
delete {{url}}/1042