@url = http://localhost:55555

### 普通get
GET {{url}}/get

### 返回json
GET {{url}}/getjson

### 普通post
POST {{url}}/post

### post带参数
POST {{url}}/postjson
Content-Type: application/json

{
    "username":"root",
    "password":"admin"
}

### 检查User-Agent
GET {{url}}/checkUserAgent